services:
  - type: web
    name: blog-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn blog_website.wsgi:application
