# Generated by Django 5.2.4 on 2025-07-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='topic_images/')),
                ('badge', models.CharField(max_length=50)),
                ('badge_color', models.CharField(max_length=50)),
            ],
        ),
    ]
